import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import test from 'node:test';
import { JSDOM } from 'jsdom';

test('node editing, directional linking, and SVG export keep the receipt splitter sample', async () => {
  const html = await readFile(new URL('../index.html', import.meta.url), 'utf8');
  const dom = new JSDOM(html, { url: 'http://localhost/' });
  const { window } = dom;
  globalThis.window = window;
  globalThis.document = window.document;
  globalThis.localStorage = window.localStorage;
  globalThis.XMLSerializer = window.XMLSerializer;
  globalThis.requestAnimationFrame = callback => setTimeout(callback, 0);
  const $ = id => window.document.getElementById(id);
  $('canvas-viewport').getBoundingClientRect = () => ({ left: 0, top: 0, width: 800, height: 800 });
  let exported;
  const originalCreateObjectURL = URL.createObjectURL;
  const originalRevokeObjectURL = URL.revokeObjectURL;
  const originalAnchorClick = window.HTMLAnchorElement.prototype.click;
  URL.createObjectURL = blob => { exported = blob; return 'blob:diagram'; };
  URL.revokeObjectURL = () => {};
  window.HTMLAnchorElement.prototype.click = () => {};
  try {
    await import('../app.js');
    for (let attempt = 0; attempt < 50 && $('layout-status').textContent !== 'Auto layout on'; attempt++) {
      await new Promise(resolve => setTimeout(resolve, 20));
    }
    assert.equal($('layout-status').textContent, 'Auto layout on');
    assert.equal(window.document.querySelectorAll('#nodes-layer .node').length, 7);
    assert.equal(window.document.querySelectorAll('.palette-item').length, 0);
    assert.equal(window.document.querySelectorAll('#edges-layer .edge').length, 8);
    assert.equal(window.document.querySelectorAll('#edge-knockouts-layer .edge-knockout').length, 8);
    assert.equal(window.document.querySelectorAll('#backings-layer .node-backing').length, 7);
    assert.equal(window.document.querySelectorAll('#nodes-layer .node-hover-outline').length, 7);
    assert.equal(window.document.querySelector('[data-node-id="n8"]'), null);
    assert.equal(window.document.querySelector('.node-label').textContent, 'MOBILE APP');
    assert.equal(window.document.querySelectorAll('#backings-layer .node-backing[mask]').length, 2);
    assert.equal(window.document.querySelectorAll('#shadows-layer .node-shadow[mask]').length, 0);
    assert.equal(window.document.querySelector('.node-shape').getAttribute('rx'), null);
    assert.ok(window.document.querySelector('.node-shadow[fill="url(#halftone)"]'));
    const fittedView = $('diagram').getAttribute('viewBox');
    $('canvas-tiles').dispatchEvent(new window.WheelEvent('wheel', { bubbles: true, cancelable: true, deltaY: -240, clientX: 400, clientY: 400 }));
    assert.ok(Number($('diagram').getAttribute('viewBox').split(' ')[2]) < Number(fittedView.split(' ')[2]));
    const zoomedX = Number($('diagram').getAttribute('viewBox').split(' ')[0]);
    $('canvas-tiles').dispatchEvent(new window.MouseEvent('pointerdown', { bubbles: true, button: 0, clientX: 400, clientY: 400 }));
    window.dispatchEvent(new window.MouseEvent('pointermove', { bubbles: true, clientX: 460, clientY: 400 }));
    window.dispatchEvent(new window.MouseEvent('pointerup', { bubbles: true, clientX: 460, clientY: 400 }));
    assert.ok(Number($('diagram').getAttribute('viewBox').split(' ')[0]) < zoomedX);
    $('zoom-fit').click();
    assert.equal($('diagram').getAttribute('viewBox'), fittedView);
    window.document.dispatchEvent(new window.KeyboardEvent('keydown', { bubbles: true, code: 'Space', key: ' ' }));
    const fixedNodeX = window.document.querySelector('[data-node-id="n1"] .node-shape').getAttribute('x');
    window.document.querySelector('[data-node-id="n1"]').dispatchEvent(new window.MouseEvent('pointerdown', { bubbles: true, button: 0, clientX: 90, clientY: 270 }));
    window.dispatchEvent(new window.MouseEvent('pointermove', { bubbles: true, clientX: 140, clientY: 270 }));
    window.dispatchEvent(new window.MouseEvent('pointerup', { bubbles: true, clientX: 140, clientY: 270 }));
    window.document.dispatchEvent(new window.KeyboardEvent('keyup', { bubbles: true, code: 'Space', key: ' ' }));
    assert.equal(window.document.querySelector('[data-node-id="n1"] .node-shape').getAttribute('x'), fixedNodeX);
    assert.notEqual($('diagram').getAttribute('viewBox'), fittedView);
    $('zoom-fit').click();

    const selectedElement = window.document.querySelector('[data-node-id="n3"]');
    selectedElement.dispatchEvent(new window.MouseEvent('click', { bubbles: true }));
    assert.equal(window.document.querySelector('[data-node-id="n3"]'), selectedElement);
    assert.equal($('inline-editor').hidden, true);
    assert.equal($('inspector-content').hidden, false);
    window.document.querySelector('[data-node-id="n3"]').dispatchEvent(new window.MouseEvent('dblclick', { bubbles: true }));
    assert.equal(window.document.querySelector('[data-node-id="n3"]'), selectedElement);
    assert.equal($('inline-editor').hidden, false);
    assert.equal($('diagram').classList.contains('editing'), true);
    assert.equal(window.document.querySelector('[data-port-id="n1-east"]').getAttribute('tabindex'), '-1');
    assert.equal($('inline-editor').value, 'API SERVER');
    assert.ok(parseFloat($('inline-editor').style.left) > 0);
    assert.ok(parseFloat($('inline-editor').style.width) > 0);
    $('inline-editor').value = 'API';
    $('inline-editor').dispatchEvent(new window.Event('input', { bubbles: true }));
    await new Promise(resolve => setTimeout(resolve, 200));
    assert.equal(JSON.parse(localStorage.getItem('schematic-editor-v2')).preset, true);
    assert.equal(window.document.querySelector('[data-node-id="n3"] .node-label').textContent, 'API');
    $('inline-editor').value = 'Updated API server';
    $('inline-editor').dispatchEvent(new window.Event('input', { bubbles: true }));
    for (let attempt = 0; attempt < 50 && window.document.querySelector('[data-node-id="n3"] .node-label').textContent !== 'UPDATED API SERVER'; attempt++) {
      await new Promise(resolve => setTimeout(resolve, 20));
    }
    assert.equal(window.document.querySelector('[data-node-id="n3"] .node-label').textContent, 'UPDATED API SERVER');
    const editedDocument = JSON.parse(localStorage.getItem('schematic-editor-v2'));
    assert.equal(editedDocument.positioned, true);
    assert.ok(editedDocument.nodes.find(node => node.id === 'n3').width > 130);
    assert.deepEqual(editedDocument.nodes.find(node => node.id === 'n1').x, 40);
    window.document.querySelector('[data-border-style="double"]').click();
    assert.equal($('inline-editor').hidden, true);
    assert.equal($('diagram').classList.contains('editing'), false);
    assert.equal(window.document.querySelector('[data-port-id="n1-east"]').getAttribute('tabindex'), '0');
    assert.equal(window.document.querySelector('[data-node-id="n3"] .node-shape').getAttribute('stroke-width'), '1');
    assert.equal(window.document.querySelector('[data-border]'), null);
    window.document.querySelector('[data-border-style="box"]').click();
    const boxGeometry = () => {
      const shape = window.document.querySelector('[data-node-id="n3"] .node-shape');
      const port = window.document.querySelector('[data-port-id="n3-east"] .port-dot');
      return [...['x', 'y', 'width', 'height'].map(name => shape.getAttribute(name)), port.getAttribute('cx'), port.getAttribute('cy')];
    };
    const singleGeometry = boxGeometry();
    assert.equal(window.document.querySelector('[data-node-id="n3"] .node-inner-border').getAttribute('stroke'), '#fff');
    window.document.querySelector('[data-border-style="double"]').click();
    assert.equal(window.document.querySelector('[data-node-id="n3"] .node-inner-border').getAttribute('stroke'), '#000');
    assert.deepEqual(boxGeometry(), singleGeometry);
    assert.equal(JSON.parse(localStorage.getItem('schematic-editor-v2')).nodes.find(node => node.id === 'n3').shape, 'double');
    window.document.querySelector('[data-border-style="text"]').click();
    assert.equal($('shadow-control').hidden, true);
    assert.equal(window.document.querySelector('[data-node-id="n3"] .node-shape').getAttribute('stroke'), 'none');
    window.document.querySelector('[data-border-style="box"]').click();
    assert.equal(window.document.querySelector('[data-node-id="n3"] .node-inner-border').getAttribute('stroke'), '#fff');
    assert.deepEqual(boxGeometry(), singleGeometry);
    const shadowsBefore = window.document.querySelectorAll('#shadows-layer .node-shadow').length;
    $('node-shadow-toggle').checked = false;
    $('node-shadow-toggle').dispatchEvent(new window.Event('change', { bubbles: true }));
    assert.equal(window.document.querySelectorAll('#shadows-layer .node-shadow').length, shadowsBefore - 1);
    assert.equal(window.document.querySelector('[aria-label="Entity shape"]')?.children.length, 4);
    window.document.querySelector('[data-border-style="database"]').click();
    const databaseNode = window.document.querySelector('[data-node-id="n3"]');
    assert.ok(databaseNode.querySelector('path.node-shape'));
    assert.ok(databaseNode.querySelector('ellipse.node-database-top'));
    assert.ok(databaseNode.querySelector('path.node-hover-outline'));
    assert.equal(databaseNode.querySelector('.node-shape').getAttribute('stroke-width'), '1');
    assert.equal(databaseNode.querySelector('.node-inner-border'), null);
    assert.equal(window.document.querySelectorAll('#backings-layer .node-backing[mask]').length, 3);
    assert.equal(window.document.querySelectorAll('#shape-masks mask').length, 3);
    $('node-shadow-toggle').checked = true;
    $('node-shadow-toggle').dispatchEvent(new window.Event('change', { bubbles: true }));
    assert.ok(window.document.querySelector('#shadows-layer .node-shadow[mask]'));
    assert.deepEqual(JSON.parse(localStorage.getItem('schematic-editor-v2')).nodes.find(node => node.id === 'n3').shape, 'database');
    assert.deepEqual([
      databaseNode.querySelector('[data-port-id="n3-east"] .port-dot').getAttribute('cx'),
      databaseNode.querySelector('[data-port-id="n3-east"] .port-dot').getAttribute('cy'),
    ], singleGeometry.slice(-2));
    $('export-svg').click();
    assert.match(await exported.text(), /class="node-database-top"/);
    assert.match(await exported.text(), /id="backing-mask-/);
    window.document.querySelector('[data-border-style="box"]').click();
    assert.deepEqual(boxGeometry(), singleGeometry);

    const sourcePort = window.document.querySelector('[data-port-id="n1-south"]');
    sourcePort.dispatchEvent(new window.MouseEvent('click', { bubbles: true }));
    window.document.querySelector('[data-port-id="n5-north"]').dispatchEvent(new window.MouseEvent('click', { bubbles: true }));
    assert.equal(window.document.querySelectorAll('#edges-layer .edge').length, 8);
    sourcePort.dispatchEvent(new window.KeyboardEvent('keydown', { bubbles: true, key: 'Enter' }));
    assert.equal($('connection-status').textContent, 'Choose a destination block');
    window.document.dispatchEvent(new window.KeyboardEvent('keydown', { bubbles: true, key: 'Escape' }));
    assert.equal($('connection-status').textContent, 'Ready to connect');
    sourcePort.dispatchEvent(new window.MouseEvent('pointerdown', { bubbles: true, button: 0, clientX: 100, clientY: 100 }));
    window.dispatchEvent(new window.MouseEvent('pointermove', { bubbles: true, clientX: 140, clientY: 120 }));
    assert.ok(window.document.querySelector('.connection-preview'));
    assert.ok(window.document.querySelector('.connection-preview-knockout'));
    window.document.querySelector('[data-port-id="n5-north"]').dispatchEvent(new window.MouseEvent('pointerup', { bubbles: true, clientX: 140, clientY: 120 }));
    for (let attempt = 0; attempt < 50 && window.document.querySelectorAll('#edges-layer .edge').length !== 9; attempt++) {
      await new Promise(resolve => setTimeout(resolve, 20));
    }
    assert.equal(window.document.querySelectorAll('#edges-layer .edge').length, 9);
    assert.equal(window.document.querySelector('.connection-preview'), null);
    assert.equal(window.document.querySelector('.connection-preview-knockout'), null);
    const newEdge = JSON.parse(localStorage.getItem('schematic-editor-v2')).edges.at(-1);
    assert.equal(newEdge.from, 'n1');
    assert.equal(newEdge.fromSide, 'south');
    assert.equal(newEdge.to, 'n5');
    assert.equal(newEdge.toSide, 'north');
    window.document.querySelector('[data-port-id="n1-east"]').dispatchEvent(new window.MouseEvent('pointerdown', { bubbles: true, button: 0, clientX: 100, clientY: 100 }));
    $('canvas-tiles').dispatchEvent(new window.MouseEvent('pointerup', { bubbles: true, clientX: 100, clientY: 100 }));
    assert.equal(window.document.querySelectorAll('#edges-layer .edge').length, 9);
    window.document.querySelector('[data-port-id="n1-east"]').dispatchEvent(new window.MouseEvent('pointerdown', { bubbles: true, button: 0, clientX: 100, clientY: 100 }));
    window.dispatchEvent(new window.MouseEvent('pointermove', { bubbles: true, clientX: 200, clientY: 200 }));
    $('canvas-tiles').dispatchEvent(new window.MouseEvent('pointerup', { bubbles: true, clientX: 200, clientY: 200 }));
    assert.equal(window.document.querySelectorAll('#edges-layer .edge').length, 9);
    const targetShape = window.document.querySelector('[data-node-id="n5"] .node-shape');
    const [viewX, viewY, viewWidth, viewHeight] = $('diagram').getAttribute('viewBox').split(' ').map(Number);
    const targetX = (Number(targetShape.getAttribute('x')) + Number(targetShape.getAttribute('width')) / 2 - viewX) * 800 / viewWidth;
    const targetY = (Number(targetShape.getAttribute('y')) + 2 - viewY) * 800 / viewHeight;
    window.document.querySelector('[data-port-id="n1-east"]').dispatchEvent(new window.MouseEvent('pointerdown', { bubbles: true, button: 0, clientX: 100, clientY: 100 }));
    window.dispatchEvent(new window.MouseEvent('pointermove', { bubbles: true, clientX: targetX, clientY: targetY }));
    window.document.querySelector('[data-node-id="n5"]').dispatchEvent(new window.MouseEvent('pointerup', { bubbles: true, clientX: targetX, clientY: targetY }));
    for (let attempt = 0; attempt < 50 && window.document.querySelectorAll('#edges-layer .edge').length !== 10; attempt++) {
      await new Promise(resolve => setTimeout(resolve, 20));
    }
    assert.equal(window.document.querySelectorAll('#edges-layer .edge').length, 10);
    assert.equal(JSON.parse(localStorage.getItem('schematic-editor-v2')).edges.at(-1).toSide, 'north');
    assert.equal(window.document.querySelector('[data-node-id="n1"] .node-shape').getAttribute('x'), '40');
    assert.equal(window.document.querySelector('[data-node-id="n4"] .node-shape').getAttribute('x'), '425');
    assert.equal(window.document.querySelector('.edge-knockout').getAttribute('stroke-width'), '18');
    $('zoom-in').click();
    assert.notEqual($('diagram').getAttribute('viewBox'), '0 0 600 600');
    $('export-svg').click();
    assert.ok(exported);
    const xml = await exported.text();
    assert.match(xml, /id="halftone"/);
    assert.match(xml, /UPDATED API SERVER/);
    assert.match(xml, /fill="#000"/);
    assert.match(xml, /Berkeley Mono/);
    assert.match(xml, /class="edge-knockout"/);
    const exportedView = xml.match(/^<svg[^>]*viewBox="([^"]+)"/)?.[1].split(' ').map(Number);
    assert.deepEqual(exportedView.slice(0, 3), [0, 0, 600]);
    assert.ok(exportedView[3] >= 600);
    assert.doesNotMatch(xml, /class="port/);
    assert.doesNotMatch(xml, /node-hover-outline/);
    assert.doesNotMatch(xml, /id="canvas-tiles"/);
    window.confirm = () => true;
    $('load-sample').click();
    await new Promise(resolve => setTimeout(resolve, 30));
    assert.equal(window.document.querySelectorAll('#nodes-layer .node').length, 7);
    assert.equal(JSON.parse(localStorage.getItem('schematic-editor-v2')).preset, true);
    const beforeDrag = window.document.querySelector('[data-node-id="n1"] .node-shape');
    const originalY = Number(beforeDrag.getAttribute('y'));
    const originalRoute = window.document.querySelector('[data-edge-id="e1"] .edge-line').getAttribute('d');
    window.document.querySelector('[data-node-id="n1"]').dispatchEvent(new window.MouseEvent('pointerdown', { bubbles: true, button: 0, clientX: 90, clientY: 270 }));
    window.dispatchEvent(new window.MouseEvent('pointermove', { bubbles: true, clientX: 90, clientY: 230 }));
    window.dispatchEvent(new window.MouseEvent('pointermove', { bubbles: true, clientX: 90, clientY: 225 }));
    assert.equal(window.document.querySelector('[data-node-id="n1"] .node-shape').getAttribute('y'), String(originalY));
    window.dispatchEvent(new window.MouseEvent('pointerup', { bubbles: true, clientX: 90, clientY: 225 }));
    const moved = window.document.querySelector('[data-node-id="n1"] .node-shape');
    assert.ok(Number(moved.getAttribute('y')) < originalY);
    assert.equal($('inline-editor').hidden, true);
    assert.notEqual(window.document.querySelector('[data-edge-id="e1"] .edge-line').getAttribute('d'), originalRoute);
    assert.equal(window.document.querySelector('[data-node-id="n4"] .node-shape').getAttribute('x'), '425');
    assert.equal(JSON.parse(localStorage.getItem('schematic-editor-v2')).positioned, true);
    window.document.querySelector('[data-node-id="n1"]').dispatchEvent(new window.MouseEvent('pointerdown', { bubbles: true, button: 0, clientX: 90, clientY: 230 }));
    window.dispatchEvent(new window.MouseEvent('pointermove', { bubbles: true, clientX: -170, clientY: -170 }));
    window.dispatchEvent(new window.MouseEvent('pointerup', { bubbles: true, clientX: -170, clientY: -170 }));
    const unboundedNode = window.document.querySelector('[data-node-id="n1"] .node-shape');
    assert.ok(Number(unboundedNode.getAttribute('x')) < 0);
    assert.ok(Number(unboundedNode.getAttribute('y')) < 0);
    $('export-svg').click();
    const unboundedSvg = await exported.text();
    const unboundedView = unboundedSvg.match(/^<svg[^>]*viewBox="([^"]+)"/)?.[1].split(' ').map(Number);
    assert.ok(unboundedView[0] < 0 && unboundedView[1] < 0);
    $('new-diagram').click();
    for (let attempt = 0; attempt < 50 && $('layout-status').textContent !== 'Auto layout on'; attempt++) {
      await new Promise(resolve => setTimeout(resolve, 20));
    }
    assert.equal(window.document.querySelectorAll('#nodes-layer .node').length, 0);
    const [canvasX, canvasY, canvasWidth, canvasHeight] = $('diagram').getAttribute('viewBox').split(' ').map(Number);
    $('canvas-tiles').dispatchEvent(new window.MouseEvent('click', { bubbles: true, clientX: 500, clientY: 350 }));
    assert.equal(window.document.querySelectorAll('#nodes-layer .node').length, 0);
    $('canvas-tiles').dispatchEvent(new window.MouseEvent('dblclick', { bubbles: true, clientX: 500, clientY: 350 }));
    assert.equal(window.document.querySelectorAll('#nodes-layer .node').length, 1);
    assert.equal($('inline-editor').hidden, false);
    let added = JSON.parse(localStorage.getItem('schematic-editor-v2')).nodes[0];
    assert.equal(added.shape, 'text');
    assert.ok(Math.abs(added.x + added.width / 2 - (canvasX + canvasWidth * 500 / 800)) < 1);
    assert.ok(Math.abs(added.y + added.height / 2 - (canvasY + canvasHeight * 350 / 800)) < 1);
    window.document.querySelector('[data-border-style="double"]').click();
    added = JSON.parse(localStorage.getItem('schematic-editor-v2')).nodes[0];
    assert.equal(added.shape, 'double');
    assert.ok(added.height > 40);
    assert.equal(window.document.querySelector('[data-node-id] .node-inner-border').getAttribute('stroke'), '#000');
    window.document.querySelector('[data-border-style="box"]').click();
    let restyled = JSON.parse(localStorage.getItem('schematic-editor-v2')).nodes[0];
    assert.deepEqual([restyled.width, restyled.height], [added.width, added.height]);
    window.document.querySelector('[data-border-style="database"]').click();
    restyled = JSON.parse(localStorage.getItem('schematic-editor-v2')).nodes[0];
    assert.ok(restyled.height > added.height);
    const databaseText = window.document.querySelector('[data-node-id] .node-label');
    const databaseTop = window.document.querySelector('[data-node-id] .node-database-top');
    assert.ok(Number(databaseText.getAttribute('y')) - 19 * 0.75 -
      (Number(databaseTop.getAttribute('cy')) + Number(databaseTop.getAttribute('ry'))) >= 8);
    window.document.querySelector('[data-node-id]').dispatchEvent(new window.MouseEvent('click', { bubbles: true }));
    assert.equal($('inline-editor').hidden, true);
  } finally {
    URL.createObjectURL = originalCreateObjectURL;
    URL.revokeObjectURL = originalRevokeObjectURL;
    window.HTMLAnchorElement.prototype.click = originalAnchorClick;
    dom.window.close();
  }
});
